//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewArray
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Move()
        {
            this.CoursesComments = new HashSet<CoursesComment>();
            this.CoursesNotes = new HashSet<CoursesNote>();
            this.CoursesQuestions = new HashSet<CoursesQuestion>();
            this.UserLearnSectionRecords = new HashSet<UserLearnSectionRecord>();
        }
    
        public int Mov_ID { get; set; }
        public int Cou_ID { get; set; }
        public bool Is_Chapter { get; set; }
        public int Chap_ID { get; set; }
        public string Chap_Name { get; set; }
        public Nullable<int> Section_ID { get; set; }
        public string Section_Name { get; set; }
    
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesComment> CoursesComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesNote> CoursesNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesQuestion> CoursesQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLearnSectionRecord> UserLearnSectionRecords { get; set; }
    }
}
